### ISSUE TITLE
OUT_OF_ENERGY

### ISSUE THREAD

**Issue by dinihou** [tronprotocol/tron-box#101]
Hi
i am try to deploy large contact - 29116 BYTES
i have 25,250,180 energy point ,but still tell me OUT_OF_ENERGY !!
how I know my need energy to deploy/trigger my contact ??!!

raport: https://api.shasta.trongrid.io/wallet/gettransactionbyid?value=a3105006b0d13d600823ec2090a92e960342f038056652189777f4020d1335dd

**Comment by Cashik** [comment]
> Hi
> i am try to deploy large contact - 29116 BYTES
> i have 25,250,180 energy point ,but still tell me OUT_OF_ENERGY !!
> how I know my need energy to deploy/trigger my contact ??!!
> 
> raport: https://api.shasta.trongrid.io/wallet/gettransactionbyid?value=a3105006b0d13d600823ec2090a92e960342f038056652189777f4020d1335dd

Have you solved this problem?

**Comment by dinihou** [comment]
Yes
Problem in shasta  testnet
I create a docker local privatenet ,
and all works
