### ISSUE TITLE
tronbox migrate error

### ISSUE THREAD

**Issue by loktarjugg** [tronprotocol/tron-box#27]
console
`tronbox migrate --reset --network shasta`
`tronbox migrate --reset`

node version v8.11.3

my tronbox.js config

```
module.exports = {
  networks: {
    development: {
// For trontools/quickstart docker image
      privateKey: '187a63bbada9ce4c9518903f88f3e4f7d1a2bd45c5a4159aec56a99733f28b39',
      consume_user_resource_percent: 30,
      fee_limit: 100000000,
      fullNode: "https://api.shasta.trongrid.io",
      solidityNode: "https://api.shasta.trongrid.io",
      eventServer: "https://api.shasta.trongrid.io",
      network_id: "*"
    },
    shasta: {
      privateKey: '187a63bbada9ce4c9518903f88f3e4f7d1a2bd45c5a4159aec56a99733f28b39',
      consume_user_resource_percent: 30,
      fee_limit: 100000000,
      fullNode: "https://api.shasta.trongrid.io",
      solidityNode: "https://api.shasta.trongrid.io",
      eventServer: "https://api.shasta.trongrid.io",
      network_id: "*"
    },
    mainnet: {
// Don't put your private key here, pass it using an env variable, like:
// PK=da146374a75310b9666e834ee4ad0866d6f4035967bfc76217c5a495fff9f0d0 tronbox migrate --network mainnet
      privateKey: process.env.PK,
      consume_user_resource_percent: 30,
      fee_limit: 100000000,
      fullNode: "https://api.trongrid.io",
      solidityNode: "https://api.trongrid.io",
      eventServer: "https://api.trongrid.io",
      network_id: "*"
    }
  }
};

```

```
Using network 'shasta'.

Running migration: 1_initial_migration.js
  Deploying Migrations...
Error encountered, bailing. Network state unknown. Review successful transactions manually.
Error: Contract has not been deployed on the network
    at /Users/jacob/.nvm/versions/node/v8.11.3/lib/node_modules/tronbox/build/webpack:/packages/tronwrap/index.js:135:1
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by sullof** [comment]
I hope that the pk you put in `tronbox.js` is not your own because this is a public forum. 

If so, it is better if you move your funds to a different address, before that someone else takes them.

If there are no funds there, tho, the migration fails like above.

If there are funds, it looks like the shasta networks was not available at that moment.

In any case, `development` using Tron Quickstart requires the Tron Quickstart witness private key to work, i.e. `da146374a75310b9666e834ee4ad0866d6f4035967bfc76217c5a495fff9f0d0`. It won't work with `187a63bbada9ce4c9518903f88f3e4f7d1a2bd45c5a4159aec56a99733f28b39`.

**Comment by loktarjugg** [comment]
@sullof thanks for your reminder,  i am using a test account

**Comment by sullof** [comment]
We just published TronBox 2.0.1, which supports the new java-tron 3.2 and fixes a couple of issues. Can you update and try again, please?
```
npm update -g tronbox
```

**Comment by sullof** [comment]
@loktarjugg I think this should be solved.
In case you still have the problem, please, reopen this issue.

**Comment by beelzebub520** [comment]
I used your way,but the problems still exist

**Comment by whitespur** [comment]
I have the same problem.I use the latest tronbox
Tronbox v2.3.0 (core: 4.1.13)
Solidity v0.4.24 (tron-solc)
node version:
v8.11.3
In my test account,I have 29444 trx,and I've frozen 20000 trx.

**Comment by sullof** [comment]
@whitespur In TronBox 2.3.0 you can see the failing transaction.
Have you looked at it? Which was the error?
