### ISSUE TITLE
can't find my deployed contract address

### ISSUE THREAD

**Issue by shapowang** [tronprotocol/tron-box#28]
tronbox migrate --reset
Using network 'development'.

Running migration: 1_initial_migration.js
  Replacing Migrations...
  Migrations:
    (base58) TV7PkRBUPwzreB7cgX9rMe7mq3uVCUmjeg
    (hex) 41d1f6b06f77eae2b20cbab9cbc3ac9e28726919f9
Saving successful migration to network...
Saving artifacts...

After this ,I still can't find my contract address on shasita testnet explorer,why?
https://explorer.shasta.trongrid.io/transaction/1a5cd7d115503e62c1e9715b69b4e9d8bb329d257cb78f8dcd601c7d3942efee

testnet address and pk:
TNx43yPrp5mitcnTwUmcVgpuRK7GniAhJT

ecf8b21fb49c20851f85d66e9f51ff2f56248a9af6bb9456cece36186782e473

**Comment by sullof** [comment]
There was a critical error in the previous version. 
We just published TronBox 2.0.1, which supports the new java-tron 3.2 and fixes a couple of issues. Can you update and try again, please?
```
npm update -g tronbox
```

**Comment by sullof** [comment]
I think you are using the wrong API. If you run

https://api.shasta.trongrid.io/wallet/gettransactionbyid?value=1a5cd7d115503e62c1e9715b69b4e9d8bb329d257cb78f8dcd601c7d3942efee

you can see the address of the contract. After run

https://api.shasta.trongrid.io/wallet/getcontract?value=41d1f6b06f77eae2b20cbab9cbc3ac9e28726919f9

and you will see that the contract has been deployed as expected.
