### ISSUE TITLE
can not transfer trx to contract in tronbox test environment

### ISSUE THREAD

**Issue by owen05** [tronprotocol/tron-box#36]
Contract code has a fallback function to receive trx
`function() payable public {}`

tronbox test js transfer trx to user address and contract address. user can receive trx，but contract can not receive 

`await tronWeb.trx.sendTransaction('contract base58 address', 20000000,{from: accounts[0]});`

**Comment by sullof** [comment]
@owen05 It looks like this is an issue with tronWeb. I will investigate it.

**Comment by sullof** [comment]
@owen05 Can you open this issue in TronWeb? https://github.com/tronprotocol/tron-web/issues
