### ISSUE TITLE
pass array args in function would cause "Invalid argument count provided"

### ISSUE THREAD

**Issue by aker0357** [tronprotocol/tron-box#39]
I try call the same contract in shasta by tronweb and tronbox with same args 
but got error in tronbox 
```    {
      "constant": false,
      "inputs": [
        {
          "name": "aa",
          "type": "uint256[]"


        }
      ],
      "name": "setValue",
      "outputs": [],
      "payable": false,
      "stateMutability": "nonpayable",
      "type": "function"
    }
  ],
``` 
the above is the function's  abi  
![2018-12-06 12 23 07](https://user-images.githubusercontent.com/7711106/49561424-2947b580-f952-11e8-9ef5-ed2d12c4c705.png)
![2018-12-06 12 25 01](https://user-images.githubusercontent.com/7711106/49561425-2a78e280-f952-11e8-8479-bd040f9409e1.png)

**Comment by sullof** [comment]
@aker0357 I will take a look asap.

**Comment by sullof** [comment]
I guess you are calling the contract in testing. Can you provide me with an example of failing test, please? Thanks.

**Comment by sullof** [comment]
I was able to replicate the issue. I am working on it.

**Comment by sullof** [comment]
I fixed it in https://github.com/tronprotocol/tron-box/pull/40/files#diff-41cd8532701b216a96264adf0b1d7ea7L417
