### ISSUE TITLE
[Proposal] Change default fee_limit in tronbox.js from 1e8 to 1e9

### ISSUE THREAD

**Issue by fyang1024** [tronprotocol/tron-box#44]
When deploying a slightly complicated contract, it usually fails due to low fee_limit. Raise the default limit might avoid that for most cases

**Comment by sullof** [comment]
You are right, but the default is there for who deploys small contracts. If you deploy a large contract, you should set your own value. From TronBox 2.2.2, you can set the `feeLimit` by contract, in `migrations/2_deploy_contracts.js`.

**Comment by VanijaDev** [comment]
Thank you, just have solved it and found your answer :)
