### ISSUE TITLE
can not catch revert error in uint test

### ISSUE THREAD

**Issue by shankj** [tronprotocol/tron-box#62]
tronbox : 2.3.1

in test_play.js

`      
       try{

            await instance.play(tronweb.sha3(uuid.v4()), payee,{
                shouldPollResponse:true
            })
            assert.fail()
        }catch(e){
            console.log(e)
        }`

tronbox test test_play.js output:
  Contract: test play.sol
    ✓ call placeDice with valid parameters (13219ms)
ERROR: REVERT opcode executed 

expect : 
test pass

tronbox 2.1.9 works

**Comment by sullof** [comment]
TronBox 2.1.9 is an "old" version. Update to 2.3.0, please.

About the issue, what do you mean? It looks like you are catching the revert (probably caused by insufficient energy or bandwidth).
Are you testing on Shasta or Tron Quickstart?

**Comment by shankj** [comment]
@sullof i already use 2.3.1. in this case instance.play with wrong params i expect should fail, so i want catch the revert, test case should pass
i am testing on tron quickstart

**Comment by sullof** [comment]
@shankj, my fault, I totally misunderstood the issue.
I will try to replicate the issue and fix it asap.

**Comment by sullof** [comment]
This https://github.com/tronprotocol/tron-box/pull/74 should solve this issue.
