### ISSUE TITLE
Please update tron-solc to at least 0.4.25 to support OpenZeppelin 1.x.x

### ISSUE THREAD

**Issue by k06a** [tronprotocol/tron-box#66]
Please update `tron-solc` to at least 0.4.25 to support OpenZeppelin 1.x.x

**Comment by sullof** [comment]
We hope to do so asap. But it depends on the java-tron team, and it's out of our control.

**Comment by maxisacoder** [comment]
what is current solc version

**Comment by lazaridiscom** [comment]
@maxisacoder , it seems like its 0.4.24 for now

https://github.com/tronprotocol/tron-box/blob/master/packages/tron-solc/package.json#L3

**Comment by bakatrouble** [comment]
@sullof No it was not:
https://github.com/tronprotocol/tron-box/blob/master/packages/tron-solc/package.json

**Comment by sullof** [comment]
That is not real data. It's an indication that has not been updated because the version comes from the compiled compiler's code.
But thanks, I will update that.

**Comment by sullof** [comment]
Btw, right now we support at most
```
pragma solidity ^0.4.25:
```

**Comment by bakatrouble** [comment]
@sullof
I've just installed `tronbox` and I'm getting this
![image](https://user-images.githubusercontent.com/7340354/54787742-c72f6980-4c3d-11e9-83d0-6b469bd67e9e.png)
Had to downgrade `openzeppelin-solidity` to 1.10.0 (latest 1.x.x is  1.12.0)
