### ISSUE TITLE
tronbox version; tronbox compile Invalid member of stdlib error

### ISSUE THREAD

**Issue by seventhelementotd** [tronprotocol/tron-box#77]
So I get an error when attempting to use tronbox commands: version, compile

tronbox version
Tronbox v2.3.9 (core: 4.1.13)
Solidity v0.4.24 (tron-solc)
(node:9960) V8: "MYPATH" npm\node_modules\tronbox\build\cli.bundled.js:171784 Invalid asm.js: Invalid member of stdlib
(node:9960) V8: "MYPATH" npm\node_modules\tronbox\build\cli.bundled.js:84002 Invalid asm.js: Invalid member of stdlib

**Comment by sullof** [comment]
That is most likely an issue with your version of Node.
