### ISSUE TITLE
Tronbox migrate error - cannot connect to TronWeb

### ISSUE THREAD

**Issue by enporter** [tronprotocol/tron-box#78]
When I try to migrate contracts using: 
`tronbox migrate --reset --network shasta`

I receive the following error: 

> ERROR: It was not possible to instantiate TronWeb. Some required parameters are missing in your "tronbox.js".

I used the default tronbox.js file, added my private key for the shasta wallet, which has shasta tron but still receive the error. What am I missing?

**Comment by nklipa13** [comment]
I had same problem because I didn't use `export` keyword in my .env file, and didn't use `source .env && tronbox migrate --reset --network shasta`

**Comment by sullof** [comment]
Alternatively you can run it as
```
PK=privateKey tronbox migrate --reset --network shasta
```

**Comment by VanijaDev** [comment]
> I had same problem because I didn't use `export` keyword in my .env file, and didn't use `source .env`
> 
> so your env file should look something like
> `export PK=your_private_key`
> 
> and then you call it like
> `source .env && tronbox migrate --reset --network shasta`

Works well! Thank you so much
