### ISSUE TITLE
Can't deploy a contract to development network

### ISSUE THREAD

**Issue by berar** [tronprotocol/tron-box#84]
This is the output: 

`ERROR: Contract Main has not been deployed on the network.
For more details, check the transaction at:
http://127.0.0.1:9090/wallet/gettransactionbyid?value=11b8b39a2ef402e64b85b52460f257499ff57b2c9c3584e497fe515486d7e3fa
If the transaction above is empty, most likely, your address had no bandwidth/energy to deploy the contract.
`

When I visit the link I get that values of: 

`"owner_address": "4182a280c3b0eed55e34067db5097e1f3c534094c2"
"origin_address": "4182a280c3b0eed55e34067db5097e1f3c534094c2"`

I run:

`sudo curl http://127.0.0.1:9090/admin/accounts?format=all`

Output is: 

`
(0) TMswWuHormhNc2BUcq84AaGotpEpDGi6Z4 (8805.74373 TRX)
    4182a280c3b0eed55e34067db5097e1f3c534094c2
(1) TM8QZcxwL9zmoaC8yf1tgL5Vei5SQYu9ZT (10000 TRX)
    417a66c73bf0461ed17721f240e1d5b2187c59f42d
(2) TXseM9Gun2sZusWKWBX7Tu26E4aizy75ua (10000 TRX)
    41f0456df2b7bb197739f063d09ffb57ea4feda5ea
(3) TQYn4d27hjuVNkfyqsMs6UgvBLkVEdRHnF (10000 TRX)
    419feb160440c6197b4465795b077659f7010aed3d
(4) TF971r13J8oPcUPkGyrG5XkhFGsutou7SX (10000 TRX)
    4138b7ca935960b35a633e084de888f3d146737210
(5) TEf9nmhSZ4a1b1YaDGRi98gsuGJ3fedAoh (10000 TRX)
    41336e75e266be5e893cca973926d8235af2d8c19b
(6) TNd3nh6cpS93JK2638fvBTguC55gycF487 (10000 TRX)
    418ac9a00961f7cccecccd11a689c931b6e0b90fb6
(7) TLayw8c1NVyMP2sbz8miucrTHhZwZyYSDD (10000 TRX)
    41747552f777d607ea45abac0976844d554b60106a
(8) TTd1DbpNTw9sTyTz3HWHnvsNKjFdzqTGhS (10000 TRX)
    41c1a01bb8b9244ee4f67788982ca3e32b7e921df9
(9) TYjd91VKXz2ebFZiTYPjt2uV8d9ZCa7Wjj (10000 TRX)
    41f9b937da5d3ada1f2b3a3f022f52d1c556659fad

Private Keys
==================

(0) b8dafcd5ed7e6b36a50efb40c4b811219ad10d88e2684976fc84931eb4d63652
(1) e41484bd5709396df86a91d5e84597aeb15675cbd3a24c6e981b0b606203f027
(2) 5910c8114dc73f4c14d85fe230918f1f14438e4c198dbe17652f90449c062f6a
(3) d61576100b877818166e4e0f2b75ed2bc6284c9d4711bcf32112f069a36dbabf
(4) 19b11b039e8207749de5d572a7c7fe3cd98b685d3c2a1f4c86013300800e3910
(5) 08c46cd3bfb5400427e1e37da8e695b2fe3fb86f125b4d02c3121120474b269b
(6) b101a1025ba78e6b6feb7df5d22bb7495d079c7152088b205ef0f97099c1977a
(7) 8545421796812cee565aee5ffa997bdf4af6c01439dbd8f8019825842e5ea3b9
(8) 70c3e8f083f58c18f05dc4dd6238f870845c48f183c54a238ddc5e06835c180a
(9) bd3a6302bf74cb8609e32b2dd5a29f31d938e28e4a6de80c26c30544fd9bb6bb

`

So it's the first address. 

So the privateKey field in the developement object is set to it:

`    development: {
// For trontools/quickstart docker image
      privateKey: 'b8dafcd5ed7e6b36a50efb40c4b811219ad10d88e2684976fc84931eb4d63652',
      userFeePercentage: 30, // or consume_user_resource_percent
      feeLimit: 100000000, // or fee_limit
      originEnergyLimit: 1e7, // or origin_energy_limit
      callValue: 0, // or call_value
      consume_user_resource_percent: 30,
      fee_limit: 100000000,

      // Requires TronBox 2.1.9+ and Tron Quickstart 1.1.16+
      fullHost: "http://127.0.0.1:9090",

      // The three settings below for TronBox < 2.1.9
      //fullNode: "http://127.0.0.1:9090",
      //solidityNode: "http://127.0.0.1:9090",
      //eventServer: "http://127.0.0.1:9090",

      network_id: "*"
    },`

Reading through these issues I read somewhere that privateKey should actually be: da146374a75310b9666e834ee4ad0866d6f4035967bfc76217c5a495fff9f0d0. 

I tried that as well, but I get the same error. But, the values of owner_address and origin_address are still the same hex for that first account. 

TronBox version is 2.3.13

**Comment by berar** [comment]
Alright, I've been going deeper at this. 

Now I run: 
`docker run -it   -p 9090:9090 -e "useDefaultPrivateKey=true"  --rm   --name tron   trontools/quickstart`

So the first address is da146374a75310b9666e834ee4ad0866d6f4035967bfc76217c5a495fff9f0d0 with about 10 billion TRX or so. 

I've been reducing the contract's code quite a bit. It used to be over 10K bytes. 

When the bytecode value is less than 5K bytes (contract size), then it migrates. So that means that then it is being deployed with some functions commented out. 

Also, there is some computation that is occurring in the constructor. The same error is shown if those lines of code are left there, even though bytecode value is < 5K bytes. So I moved those LOC into a separate function. 

I'll keep going at this. But this isn't looking promising as it leads to believe that there is quite a limit to the amount of computation for triggering smart contracts. 

Pretty sure that I'll get to deploy full code if I split it in a few contracts. But that constructor issue is bothering as it leads to assume that the same error will appear as the contract is being tested.

**Comment by sullof** [comment]
The private key used by Tron Quickstart cannot be changed. If not the deployment fails. You must stick with it.
Anyway, did you solve your problem?

**Comment by datastorm1337** [comment]
No. It's not a tronbox issue though, as it seems like that there is a limit to computations/energy tron quick start can do. 

When the contract is deployed to testnet, it's fine. 

Didn't want to dive more deeply into it. To resolve it, you'd need to look into those limits or split the contract into many smaller ones (libraries).

**Comment by berar** [comment]
No. It's not a tronbox issue though, as it seems like that there is a limit to computations/energy tron quick start can do.

When the contract is deployed to testnet, it's fine.

Didn't want to dive more deeply into it. To resolve it, you'd need to look into those limits or split the contract into many smaller ones (libraries).

**Comment by ProtonGustave** [comment]
I think reason is `feeLimit` option. I had same error but once i removed `feeValue` migration was successful.
