### ISSUE TITLE
Can't even get tronbox in terminal

### ISSUE THREAD

**Issue by zscc** [tronprotocol/tron-box#85]
I did `npm i tronbox` but get the message `command not found: tronbox`. Can someone help?

**Comment by zscc** [comment]
I figured it out. I screwed up the node modules folder when I tried to not do `sudo`. For those who also encounter this problem go check out [this video](https://www.youtube.com/watch?v=bxvybxYFq2o)

**Comment by varshakhandre14** [comment]
I was having same problem. I update node js version to 10, used it and again installed tronbox. It works! I use following commands:
nvm install 10
nvm use 10
npm install -g tronbox
