### ISSUE TITLE
ERROR: NOT_ENOUGH_EFFECTIVE_CONNECTION (effective connection:0 lt minEffectiveConnection:1) while broadcasting the transaction to create the contract Migrations

### ISSUE THREAD

**Issue by varshakhandre14** [tronprotocol/tron-box#90]
I am trying to migrate smart contract on private node using command `tronbox migrate --reset --network new_network` it is giving error 

> ERROR: NOT_ENOUGH_EFFECTIVE_CONNECTION (effective connection:0 lt minEffectiveConnection:1) while broadcasting the transaction to create the contract Migrations

When I try to deploy smart contract on shasta network, it works!
I created new network in tronbox.js file with the private key and node details.
Not getting this error's solution.

**Comment by sullof** [comment]
Where are you trying to deploy too?

**Comment by sullof** [comment]
Since a long time is passed, I suppose you solved. Feel free to re-open it not.
